import { ThemeConfig } from '../../../shared/types';

export const THEME_PRESETS: Record<string, ThemeConfig> = {
  business: {
    name: '商务专业',
    backgroundColor: '#F5F7FA',
    lineStyle: 'step',
    palette: ['#34495E', '#7F8C8D', '#2980B9', '#16A085'],
    rootStyle: {
      backgroundColor: '#2C3E50',
      color: '#FFFFFF',
      borderColor: '#2C3E50',
      borderWidth: 0,
      fontSize: 24,
      shape: 'rectangle',
      borderRadius: 2,
    },
    primaryStyle: {
      backgroundColor: '#FFFFFF',
      color: '#2C3E50',
      borderColor: '#34495E',
      borderWidth: 2,
      fontSize: 18,
      shape: 'rectangle',
      borderRadius: 2,
    },
    secondaryStyle: {
      backgroundColor: 'transparent',
      color: '#34495E',
      borderWidth: 0,
      fontSize: 14,
      shape: 'underline',
    },
  },
  fresh: {
    name: '清新薄荷',
    backgroundColor: '#FFFFFF',
    lineStyle: 'bezier',
    palette: ['#FF6B6B', '#FFE66D', '#1A535C', '#F7FFF7'],
    rootStyle: {
      backgroundColor: '#4ECDC4',
      color: '#FFFFFF',
      borderWidth: 0,
      fontSize: 24,
      shape: 'capsule',
    },
    primaryStyle: {
      backgroundColor: '#F7FFF7',
      color: '#1A535C',
      borderColor: '#4ECDC4',
      borderWidth: 2,
      fontSize: 18,
      shape: 'rounded',
      borderRadius: 16,
    },
    secondaryStyle: {
      backgroundColor: 'transparent',
      color: '#1A535C',
      borderWidth: 0,
      fontSize: 14,
      shape: 'rounded',
      borderRadius: 8,
    },
  },
  minimal: {
    name: '极简黑白',
    backgroundColor: '#FFFFFF',
    lineStyle: 'straight',
    palette: ['#000000', '#333333'],
    rootStyle: {
      backgroundColor: '#000000',
      color: '#FFFFFF',
      borderWidth: 0,
      fontSize: 24,
      shape: 'rounded',
      borderRadius: 8,
    },
    primaryStyle: {
      backgroundColor: '#FFFFFF',
      color: '#000000',
      borderColor: '#000000',
      borderWidth: 2,
      fontSize: 18,
      shape: 'underline',
    },
    secondaryStyle: {
      backgroundColor: 'transparent',
      color: '#000000',
      borderWidth: 0,
      fontSize: 14,
      shape: 'underline',
    },
  },
  vibrant: {
    name: '活力橙光',
    backgroundColor: '#FFF5F0',
    lineStyle: 'bezier',
    palette: ['#EE5253', '#FECA57', '#FF9FF3', '#54A0FF'],
    rootStyle: {
      backgroundColor: '#FF9F43',
      color: '#FFFFFF',
      borderWidth: 0,
      fontSize: 24,
      shape: 'cloud',
    },
    primaryStyle: {
      backgroundColor: '#FFFFFF',
      color: '#EE5253',
      borderColor: '#FF9F43',
      borderWidth: 3,
      fontSize: 18,
      shape: 'rounded',
      borderRadius: 12,
    },
    secondaryStyle: {
      backgroundColor: '#FFFFFF',
      color: '#EE5253',
      borderColor: '#FECA57',
      borderWidth: 1,
      fontSize: 14,
      shape: 'rounded',
      borderRadius: 8,
    },
  },
  dark: {
    name: '暗夜霓虹',
    backgroundColor: '#1E1E1E',
    lineStyle: 'straight',
    palette: ['#00FF9D', '#FF0055', '#00D2FF', '#FF00FF'],
    rootStyle: {
      backgroundColor: 'transparent',
      color: '#FFFFFF',
      borderColor: '#00FF9D',
      borderWidth: 2,
      fontSize: 24,
      shape: 'hexagon',
      shadowColor: '#00FF9D',
      shadowBlur: 10,
    },
    primaryStyle: {
      backgroundColor: 'transparent',
      color: '#FFFFFF',
      borderColor: '#FF0055',
      borderWidth: 1,
      fontSize: 18,
      shape: 'rectangle',
      shadowColor: '#FF0055',
      shadowBlur: 5,
    },
    secondaryStyle: {
      backgroundColor: 'transparent',
      color: '#00D2FF',
      borderColor: '#00D2FF',
      borderWidth: 1,
      fontSize: 14,
      shape: 'rectangle',
      shadowColor: '#00D2FF',
      shadowBlur: 3,
    },
  }
};
